### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3385
Changed screenshot

### CODE REVIEW

**Review by Reeced40 — COMMENTED** [review]
Changed screenshot.

**Comment by mypil** [comment]
@nenonix - can you please assist to check on this PR and let us know if its good to go? Thanks.

**Comment by nenonix** [comment]
LGTM

**Comment by mypil** [comment]
looping in @get-itips so he can help guide and share his insights on this PR. Please assist to review this PR based on issue [3385](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3385) and let @Reeced40 know what needs to be changed or improved. Thank you.

**Comment by get-itips** [comment]
Hello @Reeced40 how are you? I reviewed the screenshot and it contains information about a third party antivirus. So the screenshot might not be useful for official documentation.
Please take the screenshot from another Windows 10 clean install.

**Pull request closed without merging**
